line-length = 99
target-version = "py313"
output-format = "grouped"

[lint]
allowed-confusables = ["'", "’", "×", "–", "‘"]
select = ["ALL"]
ignore = [
    "D203", "D213", "TID252", "S101", "INT001",
    "COM812", "ISC001", "Q000", "Q003",
    "RUF100",
    "RUF102",
    "ARG",
    "ERA",
    "S105", "S106",
    "S311",
    "S308",
    "S610",
    "E731", "B023",
    "B024",
    "BLE001",
    "FIX002", "TD003",
    "G", "EM", "TRY",
]

[lint.pycodestyle]
max-doc-length = 79

[lint.isort]
combine-as-imports = true
detect-same-package = true
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
order-by-type = true

[lint.pep8-naming]
classmethod-decorators = ["classmethod"]
